let a=Number(5)
let b=Number(-1)
let c=Number("hello")
let o=String(55)
let i=String(-10)
let d=String(0)
document.writeln(a)
document.writeln(b)
document.writeln(c)
document.writeln(o)
document.writeln(i)
document.writeln(d)